spring.datasource.url=jdbc:postgresql://localhost:5432/kirana_db
spring.datasource.username=kirana_user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.data.mongodb.uri=mongodb+srv://soneshsrivenkat_db_user:LEYGZU6ppwenEgpO@cluster0.x2aay8e.mongodb.net/kirana?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

spring.cache.type=redis

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.data.redis.timeout=60000


# ===============================
# KAFKA CONFIGURATION
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

# Producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer
spring.kafka.consumer.group-id=reporting-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Important for JSON conversion
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.demo.events



rate-limit.limits.transaction.USER.capacity=10
rate-limit.limits.transaction.USER.duration=60

rate-limit.limits.transaction.ADMIN.capacity=50
rate-limit.limits.transaction.ADMIN.duration=60


rate-limit.limits.product.USER.capacity=20
rate-limit.limits.product.USER.duration=60

rate-limit.limits.product.ADMIN.capacity=100
rate-limit.limits.product.ADMIN.duration=60



rate-limit.limits.sales.USER.capacity=15
rate-limit.limits.sales.USER.duration=60

rate-limit.limits.sales.ADMIN.capacity=60
rate-limit.limits.sales.ADMIN.duration=60



rate-limit.limits.refund.USER.capacity=5
rate-limit.limits.refund.USER.duration=60

rate-limit.limits.refund.ADMIN.capacity=25
rate-limit.limits.refund.ADMIN.duration=60


rate-limit.limits.auth.USER.capacity=5
rate-limit.limits.auth.USER.duration=60

rate-limit.limits.auth.ADMIN.capacity=10
rate-limit.limits.auth.ADMIN.duration=60



